### PR TITLE
Mengting login/signup pages

### PR DESCRIPTION
**Pull request by MengtingCao**
Implemented basic html and css design for [login, signup, forgot password, change password](https://mchso-infoorganizer.atlassian.net/jira/software/c/projects/MCHSO/boards/1?modal=detail&selectedIssue=MCHSO-45), and [edit account](https://mchso-infoorganizer.atlassian.net/jira/software/c/projects/MCHSO/boards/1?modal=detail&selectedIssue=MCHSO-44) pages.

### CODE REVIEW

**Comment by jswood23** [comment]
In the deployment on the login page, it looks like the "Sign Up" button is not the correct size. Is this intentional?

**Review by jswood23 — CHANGES_REQUESTED** [review]
Looks good overall, but I think we should move the styles for the buttons and links into their own file for easier reference since we'll be using them in various places across the website.

**Comment by jswood23** [comment]
Here's a webpage talking about good file structuring for rails css files: [https://www.bitesite.ca/blog/ruby-on-rails-css-file-structure](https://www.bitesite.ca/blog/ruby-on-rails-css-file-structure)

**Review by jswood23 — APPROVED** [review]
Everything's good, I'll start working on file structure in an upcoming PR.

**Review by NR229 — APPROVED** [review]
Review app looks great, good work

**Pull request merged**
