### PR TITLE
Yuning about page

### PR DESCRIPTION
**Pull request by ynzhang09**
Added basic information about org to the about page

### CODE REVIEW

**Review by jswood23 — APPROVED** [review]
Looks good

**Comment by jswood23** [comment]
The build failed because the heroku changes haven't been made yet in this branch. There's nothing wrong with this code.

**Comment by jswood23** [comment]
Make sure to resolve the conflicts using this command:
```
git pull --rebase upstream development
```

**Review by MengtingCao — APPROVED** [review]
Looks good

**Pull request merged**
