### PR TITLE
Juliana internal contact

### PR DESCRIPTION
**Pull request by julianaLeano**
Having some issues with the event integration tests for some reason but everything else should be good

### CODE REVIEW

**Review by jswood23 — CHANGES_REQUESTED** [review]
In the contact list, if a user has no contact picture, it shows the url-not-found image. Could we add logic there to check if there is a contact picture url and display the generic profile image if not? You can find code for the generic profile image on line 93 of `_nav_bar.html.erb`. I think we should also replace the "Picture" header with a blank header.
Screenshot 2022-11-07 153424

**Comment by jswood23** [comment]
Good fix, but it looks like the search results page needs the same change.

**Review by jswood23 — APPROVED** [review]
Great work, everything looks good.

**Review by MengtingCao — APPROVED** [review]
Code looks good. Was unable to check website.

**Pull request merged**
