### PR TITLE
Yuning about page design

### PR DESCRIPTION
**Pull request by ynzhang09**
This pull request corresponds to this user story: [https://mchso-infoorganizer.atlassian.net/browse/MCHSO-31](url)
It provides design and styling for the about page.

Acceptance Criteria:

- Is mobile and PC friendly

- color scheme consistent across pages

Definition of Done:

- Reviewed by the product owner

- 100% code coverage

- Satisfies acceptance criteria

- Deployed on website

### CODE REVIEW

**Review by jswood23 — CHANGES_REQUESTED** [review]
I like the overall style, but there are a few things that still need to change:
- The buttons are not consistent with the rest of the site. To fix this, just add the line `@import url("./components/buttons.css");` to the top and change the class of the buttons to either `pink_button` or `black_button`.
- We decided on Sansita One as the font for only headers, not all text. We've already styled the headers in a separate file, so all you need to do is add the line `@import url("./components/fancy_headers.css");` to the top of your `about.css` file.
- For some reason, in the review app the information that is supposed to be in bullet point format is coming up in list format. I assume it was working on your local device, so I'm not entirely sure what's causing this.
- In the individual headers for each section, it simply lists the name of the variable in lowercase with underscores. Is there a function we could either call or create that converts this to capitalized with spaces?

**Comment by jswood23** [comment]
Make sure to put `text-decoration: none` on the links in the buttons to remove the underline.

**Comment by ynzhang09** [comment]
-Button and header formatting have been updated 
-Decided to remove bullet point information for now to make content more consistent with rest of the about page and to fit the overall style of the page
-For individual headers: Changed db seed formatting - since the page data attribute is a string, it can be easily changed to uppercase and contain spaces, making it easier for officers to update pages without worrying about formatting issues

**Review by MengtingCao — CHANGES_REQUESTED** [review]
- Expectations description contains brackets and single quotes, we should change that.
- “What_we_do” should not have underscores in place of spaces.
- What_we_do description contains brackets and single quotes, we should change that.

**Review by MengtingCao — CHANGES_REQUESTED** [review]
- Have consistent capitalization method for 'Expectations' and 'What We Do' descriptions
- Mobile view is not implemented

**Comment by MengtingCao** [comment]
> * Have consistent capitalization method for 'Expectations' and 'What We Do' descriptions
> * Mobile view is not implemented

image

**Comment by MengtingCao** [comment]
> * Have consistent capitalization method for 'Expectations' and 'What We Do' descriptions
> * Mobile view is not implemented

image

**Comment by ynzhang09** [comment]
-Changed capitalization and implemented mobile layout

**Review by MengtingCao — APPROVED** [review]

**Review by jswood23 — APPROVED** [review]
Good work, I like how the resizing works. While I'd prefer to have a container box, I do think that this style works just fine without one and everything looks good and professional.

**Pull request merged**
