### PR TITLE
Sprint 3 Release Into Production

### PR DESCRIPTION
**Pull request by jswood23**
This PR merges all of the Sprint 3 commits from the development branch into the production branch.

### CODE REVIEW

**Review by ynzhang09 — APPROVED** [review]
Looks good

**Review by MengtingCao — APPROVED** [review]
looks good

**Review by MengtingCao — CHANGES_REQUESTED** [review]
Home page has no text

**Comment by jswood23** [comment]
> Home page has no text

This was due to database seeds and not an issue in the code.

**Pull request merged**
