### PR TITLE
added google login to login page

### PR DESCRIPTION
**Pull request by MengtingCao**
I finished up implementing google login

### CODE REVIEW

**Comment by jswood23** [comment]
What happens when the user creates an account? What goes into our system?

**Review by jswood23 — APPROVED** [review]

**Comment by MengtingCao** [comment]
> What happens when the user creates an account? What goes into our system?

**Comment by MengtingCao** [comment]
I believe anyone can create an account right now even if they don’t log in with google. we could get rid of the create account button if we need to.

**Review by ynzhang09 — APPROVED** [review]
Looks good

**Pull request merged**
